name: Check style

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: npm --prefix ./app ci --only=development
      - run: npm --prefix ./app run check-format
  
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: npm --prefix ./app ci --only=development
      - run: npm --prefix ./app run lint
